require_relative 'cooking'

#namespace keeps our task separate from others
namespace :cooking do

  #Adding a desc means that our task will show up in rake -T
  # EGGS is an optional environment variable passed in
  desc "Make breakfast! usage:'rake EGGS=3 cooking:breakfast['Customer Name']'"

  #breakfast expects a customer param and depends on three other
  #tasks before it can start
  task :breakfast, [:customer] => [:orange_juice, :ham, :eggs] do |t,args|

    #We can have some default args
    args.with_defaults(:customer => 'Anonymous')
    
    #And we can use the args
    puts "Here's #{args.customer}'s breakfast!!!"
  end

  #Tasks without desc are not shown in rake -T
  task :eggs do
    Cooking.cook_eggs ENV["EGGS"] || 2
  end

  task :ham do
    Cooking.slice_ham
  end

  task :orange_juice =>[:pick_oranges] do
    Cooking.squeeze_oranges
  end

  task :pick_oranges do
    puts "Off to the orange grove!"
  end

  # We can reopen and extend tasks
  task :pick_oranges do
    puts "Picking Oranges..."
  end
end
